---
- hosts: jails
  become_user: root
  become_method: su
  become: true
  gather_facts: no
  vars:
    ansible_python_interpreter: "/usr/local/bin/python"
  environment:
    ASSUME_ALWAYS_YES: "yes"
  roles:
    - bootstrap
    - jailmaster 
    - flavor
  pre_tasks:
    - name: debug some variables
      debug:
        var: "{{ item }}"
      with_items:
        - ronald
        - masterserver_ip
        - masterserver_interface
        - jails_ip_block
