- name: Add resolv.conf to masterserver
  template:
    src: usr/jails/masterserver/etc/resolv.conf
    dest: /usr/jails/masterserver/etc/resolv.conf
    mode: 0644
  tags:
   - jexec
   - dns
   - unbound

- name: Build the master server
  shell: "{{ item }}"
  with_items:
   - jexec {{ masterserver_jail_name }} pkg install perl5 python27 vim screen shellinabox portupgrade vsftpd-ext bind910
   - jexec {{ masterserver_jail_name }} portinstall --batch sudo bash zsh unbound textmaze
  tags: jexec

- name: Create unbound config dir
  file:
    path: /usr/jails/{{ masterserver_jail_name }}/usr/local/etc/unbound
    state: directory
  tags:
   - jexec
   - unbound

- name: Enable local DNS server for use by all trainees
  template:
    src: usr/local/etc/unbound/unbound.conf.j2
    dest: /usr/jails/{{ masterserver_jail_name }}/usr/local/etc/unbound/unbound.conf
    owner: root
    mode: 0644
  tags:
   - jexec
   - unbound

- name: Add unbound to start at FreeBSD boot
  shell: jexec {{ masterserver_jail_name }} sysrc unbound_enable=YES
  tags:
   - jexec
   - unbound

- name: Start unbound
  command: jexec {{ masterserver_jail_name }} service unbound start
  tags:
   - jexec
   - unbound

